### ISSUE TITLE
dont cant send message media group,newslattest,private

### ISSUE THREAD

**Issue by StartGrow** [nstar-y/bail#4]
Media upload failed on all hosts
    at /home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:636:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upload (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:705:36)
    at async /home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:123:28
    at async Promise.all (index 0)
    at async prepareWAMessageMedia (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:121:48)
    at async generateWAMessageContent (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:376:13)
    at async generateWAMessage (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:528:59)
    at async Object.sendMessage (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:690:33)
    at async conn.sendFile (/home/container/lib/simple.js:914:15)
    at async Object.handler (/home/container/handler.js:947:13) {

**Comment by nstar-y** [comment]
it works for me and other users, there have been no other reports like that yet
